# Generated by Django 5.0.7 on 2024-07-31 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_consultation_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("institute", models.CharField(blank=True, max_length=100, null=True)),
                ("whatsapp_no", models.CharField(blank=True, max_length=15, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                            ("Rather Not Say", "Rather Not Say"),
                        ],
                        default="Rather Not Say",
                        max_length=20,
                    ),
                ),
                (
                    "fathers_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mothers_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("course", models.CharField(blank=True, max_length=100, null=True)),
                ("semester", models.CharField(blank=True, max_length=10, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
