# Generated by Django 4.2.14 on 2024-07-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenity_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddField(
            model_name='property',
            name='bus_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_name',
            field=models.CharField(default='NixStays Team', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_number',
            field=models.CharField(default='8449922025', max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default="We're dedicated to give you best customer service", max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='food_menu',
            field=models.ImageField(blank=True, null=True, upload_to='food_menu/'),
        ),
        migrations.AddField(
            model_name='property',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='hostel_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='housekeeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='laundry_service',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.CharField(default='Gr. Noida', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_market',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_metro_station',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='new_price',
            field=models.DecimalField(decimal_places=0, default=465, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='old_price',
            field=models.DecimalField(decimal_places=0, default=625, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='other_facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='staff',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('ac_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_ac_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='main.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institute')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_inst', to='main.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='main.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='main.amenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_institutes',
            field=models.ManyToManyField(through='main.PropertyInstitute', to='main.institute'),
        ),
    ]
