# Generated by Django 4.2.14 on 2024-07-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_amenity_institute_remove_property_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='new_price',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='old_price',
            field=models.DecimalField(decimal_places=0, default=120000, max_digits=10),
        ),
    ]
