# Generated by Django 4.2.14 on 2024-08-02 14:56

from django.db import migrations, models
import django.utils.timezone

def set_default_dates(apps, schema_editor):
    Property = apps.get_model('main', 'Property')
    now = django.utils.timezone.now()
    Property.objects.update(created_at=now, updated_at=now)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_food_remove_property_food_type_property_food_type'),  # Updated dependency
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(set_default_dates),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]

