# Generated by Django 4.2.14 on 2024-08-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile_dp_userprofile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='NixStays Team', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_number',
            field=models.CharField(default='8449922025', max_length=15),
        ),
    ]
